### PR TITLE
Bump to version 1.2.1

### PR DESCRIPTION
**Pull request by rhpvorderman**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Also added @DavyCats and @sndrtj as maintainers to improve the bus factor.

@conda-forge-admin, please rerender

**Comment by rhpvorderman** [comment]
Also added @DavyCats and @sndrtj as maintainers to improve the bus factor.

**Review by sndrtj — APPROVED** [review]

**Comment by mariusvniekerk** [comment]
@DavyCats can you approve as well?

**Review by DavyCats — APPROVED** [review]
Oh I thought I already had, sorry :s

**Pull request merged**
